version: '3.8'
services:
  postgresdb:
    image: postgres:15
    container_name: fxdealmanager-db
    restart: always
    environment:
      POSTGRES_DB: fxdealdb
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
